- include: ubuntu.yml
  when: ansible_os_family == 'Debian'

- include: macos.yml
  when: ansible_os_family == 'Darwin'

- name: Check if Tmux Plugin Manager is installed
  vars:
    tmux_tpm_dir: ~/.config/tmux/plugins/tpm
  ansible.builtin.stat:
    path: "{{ tmux_tpm_dir }}"
  register: tmux_tpm_exists

- name: Install Tmux Plugin Manager
  vars:
    tmux_tpm_dir: ~/.config/tmux/plugins/tpm
  ansible.builtin.command:
    "git clone https://github.com/tmux-plugins/tpm {{ tmux_tpm_dir }}"
  when: not tmux_tpm_exists.stat.exists
